name: Publish Package & Docs

on:
  release:
    types: [published]
  workflow_dispatch:   # Enable manual trigger.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Mandatory for OIDC.
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest

      - name: Build package
        run: uv build

      - name: Generate release notes
        run: python devtools/release_notes.py > ${{ github.workspace }}-RELEASE_NOTES.md

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-RELEASE_NOTES.md
          prerelease: ${{ contains(env.TAG, 'rc') }}

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
